name: Multiple compilers and versions

on:
  workflow_call:

jobs:
  my_matrix:
    name: Compiler test
    strategy:
      fail-fast: false
      matrix:
        include:
          - CC: gcc-9
            CXX: g++-9
          - CC: gcc-10
            CXX: g++-10
          - CC: gcc-11
            CXX: g++-11
          - CC: gcc-12
            CXX: g++-12
          - CC: clang-12
            CXX: clang++-12
          - CC: clang-13
            CXX: clang++-13
          - CC: clang-14
            CXX: clang++-14
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        env:
            CC: ${{ matrix.CC }}
            CXX: ${{ matrix.CXX }}
        run: ./autogen.sh && ./configure && make && make dist
